# properties file for testing accelerator
api_key=xxxx # set env variable CEDAR_API_KEY
cedar_endpoint=https://resource.metadatacenter.org
chords_folder=xxxx # set the test folder target here as CEDAR_FOLDER_ID

